### ISSUE TITLE
Boostrap really need to use "root" user could it just user become true and become methode sudo and remote_user that I specified

### ISSUE THREAD

**Issue by BuhtigithuB** [robertdebock/ansible-role-bootstrap#54]
The current bootstrap implementation is breaking my ansible flow...

I only want to install xrdp and ends out needing 3 dependencies roles... I would be easier to render xrdp role self contained...

TASK [robertdebock.bootstrap : install bootstrap packages] ********************************************************************************************************************************************************
tes - mkstemp (13: Permission denied)\nE: Failed to write temporary StateFile /var/lib/apt/extended_states\n", "rc": 100, "stderr": "E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp failed: [10.2.24.27] (item=gnupg) => {"ansible_loop_var": "item", "changed": false, "item": "gnupg", "msg": "'/usr/bin/apt-mark manual gnupg' failed: E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)\nE: Failed to write temporary StateFile /var/lib/apt/extended_states\n", "rc": 100, "stderr": "E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)\nE: Failed to write temporary StateFile /var/lib/apt/extended_states\n", "stderr_lines": ["E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)", "E: Failed to write temporary StateFile /var/lib/apt/extended_states"], "stdout": "gnupg set to manually installed.\n", "stdout_lines": ["gnupg set to manually installed."]}
ded_states - mkstemp (13: Permission denied)\nE: Failed to write temporary StateFile /var/lib/apt/extended_states\n", "stderr_lines": ["E: Could not create temporary file for /var/lib/apt/extended_states - mkste

Ubuntu 18.04 (manage node and master node)

**Comment by roberthorn** [comment]
My team is seeing the same error in our workflow on Ubuntu 18.04. For our use-case, the role executes successfully on a new host, but additional configuration code is changing permissions that is causing the above error on a subsequent run if the installed packages have been changed in any way.

Would it be possible to somehow allow the user of the role to specify to not override `become_user` with `ansible_user` for installing the necessary packages? For us the error goes away if `become_user` is still `root`. Connecting as `root` is not an option for us.

**Comment by robertdebock** [comment]
I'll have a look, sorry for the issue, thanks for the feedback.

**Comment by robertdebock** [comment]
About the xrdp role; you _can_ prepare a system with the roles listed in the README.md, but you can also prepare a system differently. Most people do prepare a system differently, that's why almost no role use `dependencies:` in `meta/main.yml`.

About the issue reported; I can't reproduce it. Can I ask you to show me the playbook and variables applicable to reproduce the issue?

Regards, Robert.

**Comment by robertdebock** [comment]
And; was there ever a version of this role that has worked for you?

**Comment by roberthorn** [comment]
I'm able to reproduce with a Vagrant environment using the same play configuration from `molecule/converge.yml`
```
vagrant init ubuntu/bionic
vagrant up
ansible-playbook -i '127.0.0.1:2200,' --private-key ./.vagrant/machines/default/virtualbox/private_key -b -u vagrant play.yml
```

It seems like #53 is a related issue, the issue being that your have to be `root` to install packages, but the `install bootstrap packages (package)` is becoming the remote user. It seems like since the role assumes that `sudo` is not available, you *have* to run as root.

**Comment by blaisep** [comment]
Edit: My scenario was a bit different. I had disabled the `root` account at (Fedora) installation.
Workaround: enable the `root` account, but disable ssh login. So `become` uses the `sudo` method.

> And; was there ever a version of this role that has worked for you?

The golden question! I always suspect selinux... I'm getting this on a fresh Fedora 35 server:

```
TASK [robertdebock.bootstrap : install bootstrap packages (package)] *********************************************************************************************
failed: [localhost] (item=python3) => {"ansible_loop_var": "item", "changed": false, "item": "python3", "msg": "This command has to be run under the root user.", "results": []}
failed: [localhost] (item=sudo) => {"ansible_loop_var": "item", "changed": false, "item": "sudo", "msg": "This command has to be run under the root user.", "results": []}
```

**Comment by flybyray** [comment]
> I'm able to reproduce with a Vagrant environment

Me too. Used the robertdebock.development_environment collection the Vagrant.libvirt with fedora-35.

A workarround was to explicit set become_user to root.
https://github.com/robertdebock/ansible-role-bootstrap/blob/master/tasks/main.yml#L67

**Comment by isuftin** [comment]
I can confirm that I am also seeing the "This command has to be run under the root user." issue for python3 and sudo on bento/centos-8 and generic/rhel8  via vagrant+virtualbox when just having this role run on a brand new VM. I've tried multiple variations of become_user, become_method, become, bootstrap_user, etc

I keep hitting:

```
TASK [robertdebock.bootstrap : install bootstrap packages (package)] ***********
Tuesday 01 February 2022  12:07:34 -0600 (0:00:01.214)       0:00:03.702 ******
failed: [vagrant-centos8-starter-role] (item=python3) => changed=false
  ansible_loop_var: item
  item: python3
  msg: This command has to be run under the root user.
  results: []
failed: [vagrant-centos8-starter-role] (item=sudo) => changed=false
  ansible_loop_var: item
  item: sudo
  msg: This command has to be run under the root user.
  results: []
```

Edit: I should add this works fine on bento/centos-7

Edit 2: Rolled back to version 5.2.3 and that seems to work fine

**Comment by robertdebock** [comment]
The difference between `master` and `5.2.3` is [mostly](https://github.com/robertdebock/ansible-role-bootstrap/compare/5.2.3...5.2.12#diff-3d0ff1709ca48add100327bb2a468e6c508fb92a159c64c4f99ad1df89d9bddeL65-L66):

5.2.3 (Working)
```
  vars:
    ansible_user: "{{ bootstrap_ansible_user | default(omit) }}"
```

latest (Broken)
```
  become: yes
  become_user: "{{ bootstrap_ansible_user | default(bootstrap_user) }}"
```

Let me revert that part.

It's difficult to automatically test this; the containers I use are root by default.

**Comment by flybyray** [comment]
> It's difficult to automatically test this; the containers I use are root by default.

It would make sense to have a specialized Dockerfiles.j2 file for the molecule scenarios to adapt to the vagrant-libvirt based images with a non-priviledged-user. I use it quite frequently in that way to test roles. Was one of the first things I did when testing your roles - switching to official centos/almalinux images which are enhanced and prepared by the molecule docker driver on the fly and even the reuse of already build images ( cached ) works.

see for details:
https://molecule.readthedocs.io/en/latest/examples.html#docker-with-non-privileged-user

**Comment by robertdebock** [comment]
With version 6.0.0 (released yesterday) this issue should be resolved. Thanks all for helping!

**Comment by hockeymikey** [comment]
@robertdebock Nope, it did not. https://github.com/robertdebock/ansible-role-bootstrap/commit/c7cc6d4eeff4c64584d76a5c1d9964e7b5395d15 Broke it again. I reverted your changes and it fixed it.

**Comment by dgibbs64** [comment]
Can also confirm on Alma Linux 8
```
failed: [almalinux8.examle.com] (item=python3) => {"ansible_loop_var": "item", "changed": false, "item": "python3", "msg": "This command has to be run under the root user.", "results": []}
```

**Comment by isuftin** [comment]
This is still broken for RHEL 8. Seems to work fine for CentOS 7 for some reason?
